import React,{useState}from'react';import{createRoot}from'react-dom/client';import'../css/app.css';

const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.content;
async function post(url,data={},method='POST'){const r=await fetch(url,{method,headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrf(),'Accept':'application/json'},body:JSON.stringify(data)});if(r.redirected)location.href=r.url;return r;}

function Field({label,name,type='number',required=false,value,onChange}){return <div className="field"><label>{label}</label><input name={name} type={type} step={type==='number'?'any':undefined} required={required} value={value??''} onChange={onChange}/></div>}

function AnalysisApp(){const[doForm,setDoForm]=useState({sample_code:'',thiosulfate_ml:'',thiosulfate_duplo_ml:'',normality:'',winkler_volume_ml:'',reagent_mnso4_ml:'1',reagent_alkali_ml:'1',aliquot_ml:'50'});const[bodForm,setBodForm]=useState({sample_code:'',a1:'',a2:'',b1:'',b2:'',vb:'',vc:'',p:'',sample_ph:'',sample_temperature:'',storage_temperature:'',storage_hours:'',gga_bod:''});const[message,setMessage]=useState('');
const set=(setter)=>(e)=>setter(v=>({...v,[e.target.name]:e.target.value}));
const submit=(url,data)=>async e=>{e.preventDefault();setMessage('Memproses...');const r=await post(url,data);setMessage(r.ok?'Data berhasil diproses.':'Validasi atau proses gagal.');if(r.ok)location.reload()};
return <div className="app-shell"><header className="topbar"><div className="container topbar-inner"><div><b>Laboratory Analysis</b><div style={{fontSize:12,opacity:.85}}>DO · BOD₅ · QC · Uncertainty</div></div><div>{window.LAB_USER_NAME||'User'} · {window.LAB_USER_ROLE||''}</div></div></header><main className="container" style={{padding:'22px 0 40px'}}><div className="actions no-print" style={{marginBottom:16}}><a className="btn btn-secondary" href="/analysis">Dashboard</a><a className="btn btn-secondary" href="/superadmin/laboratories">Laboratorium</a><form method="post" action="/logout"><input type="hidden" name="_token" value={csrf()}/><button className="btn btn-secondary">Logout</button></form></div>{message&&<div className="card" style={{marginBottom:16}}>{message}</div>}<div className="grid grid-2"><section className="card"><h2>Analisis DO</h2><form onSubmit={submit('/analysis/do',doForm)}><div className="grid grid-2">{Object.entries(doForm).map(([k,v])=><Field key={k} label={k.replaceAll('_',' ')} name={k} required={!k.includes('duplo')} value={v} onChange={set(setDoForm)}/>)}</div><button className="btn btn-primary">Hitung DO</button></form></section><section className="card"><h2>Analisis BOD₅</h2><form onSubmit={submit('/analysis/bod',bodForm)}><div className="grid grid-2">{Object.entries(bodForm).map(([k,v])=><Field key={k} label={k.replaceAll('_',' ')} name={k} required={['sample_code','a1','a2','b1','b2','vb','vc','p'].includes(k)} value={v} onChange={set(setBodForm)}/>)}</div><button className="btn btn-primary">Hitung & Simpan BOD₅</button></form></section></div><section className="card" style={{marginTop:16}}><h2>Ketidakpastian Top-Down</h2><p style={{color:'#667085'}}>Gunakan data precision dan bias hasil validasi/QC.</p><a className="btn btn-secondary" href="/analysis">Buka modul uncertainty</a></section></main></div>}

function Master({type}){const cfg={samples:{title:'Master Sample',items:window.MASTER_ITEMS||[],action:'/masters/samples',fields:[['sample_code','Kode sample','text'],['sample_name','Nama sample','text'],['matrix','Matrix','text'],['received_at','Diterima','datetime-local'],['customer','Customer','text'],['notes','Catatan','text']]},reagents:{title:'Master Reagen',items:window.MASTER_ITEMS||[],action:'/masters/reagents',fields:[['code','Kode','text'],['name','Nama','text'],['lot_number','No. lot','text'],['concentration','Konsentrasi','number'],['unit','Satuan','text'],['expiry_date','Expiry','date']]},instruments:{title:'Master Instrumen',items:window.MASTER_ITEMS||[],action:'/masters/instruments',fields:[['code','Kode','text'],['name','Nama','text'],['serial_number','Serial number','text'],['calibration_due','Kalibrasi','date']]}}[type];return <main className="container" style={{padding:'24px 0'}}><div className="actions"><a className="btn btn-secondary" href="/analysis">Analisis</a><a className="btn btn-secondary" href="/masters/samples">Sample</a><a className="btn btn-secondary" href="/masters/reagents">Reagen</a><a className="btn btn-secondary" href="/masters/instruments">Instrumen</a></div><section className="card" style={{marginTop:16}}><h1>{cfg.title}</h1><form method="post" action={cfg.action}><input type="hidden" name="_token" value={csrf()}/><div className="grid grid-3">{cfg.fields.map(f=><Field key={f[0]} label={f[1]} name={f[0]} type={f[2]} required={f[0]==='code'||f[0]==='sample_code'||f[0]==='name'}/>)}</div>{type==='instruments'&&<div className="field"><label>Status</label><select name="status"><option>active</option><option>maintenance</option><option>expired</option></select></div>}<button className="btn btn-primary">Simpan</button></form></section><section className="card"><div className="table-wrap"><table className="table"><thead><tr>{cfg.fields.slice(0,5).map(f=><th key={f[0]}>{f[1]}</th>)}<th>Aksi</th></tr></thead><tbody>{cfg.items.map(x=><tr key={x.id}>{cfg.fields.slice(0,5).map(f=><td key={f[0]}>{x[f[0]]??'-'}</td>)}<td><form method="post" action={`${cfg.action}/${x.id}`}><input type="hidden" name="_token" value={csrf()}/><input type="hidden" name="_method" value="DELETE"/><button className="btn btn-danger">Hapus</button></form></td></tr>)}</tbody></table></div></section></main>}

function Login(){return <main className="container" style={{minHeight:'100vh',display:'grid',placeItems:'center'}}><div className="card" style={{width:'min(430px,100%)'}}><h1>Laboratory Information System</h1><p>DO · BOD₅ · Measurement Uncertainty</p>{window.FLASH_ERROR&&<div className="card">{window.FLASH_ERROR}</div>}<form method="post" action="/login"><input type="hidden" name="_token" value={csrf()}/><div className="field"><label>Email</label><input name="email" type="email" required/></div><div className="field"><label>Password</label><input name="password" type="password" required/></div><button className="btn btn-primary" style={{marginTop:12,width:'100%'}}>Login</button></form></div></main>}

function Users(){const users=window.USERS||[];return <main className="container" style={{padding:'24px 0'}}><div className="actions"><a className="btn btn-secondary" href="/analysis">Analisis</a><form method="post" action="/logout"><input type="hidden" name="_token" value={csrf()}/><button className="btn btn-secondary">Logout</button></form></div><section className="card" style={{marginTop:16}}><h1>User & Role Management</h1><form method="post" action="/admin/users"><input type="hidden" name="_token" value={csrf()}/><div className="grid grid-3"><Field label="Nama" name="name" type="text" required/><Field label="Email" name="email" type="email" required/><Field label="Password" name="password" type="password" required/><div className="field"><label>Role</label><select name="role"><option>analyst</option><option>supervisor</option><option>admin</option><option>viewer</option></select></div></div><button className="btn btn-primary">Tambah User</button></form></section><section className="card"><div className="table-wrap"><table className="table"><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.role}</td><td>{u.active?'Aktif':'Nonaktif'}</td><td><form method="post" action={`/admin/users/${u.id}`}><input type="hidden" name="_token" value={csrf()}/><input type="hidden" name="_method" value="DELETE"/><button className="btn btn-danger">Hapus</button></form></td></tr>)}</tbody></table></div></section></main>}

function Laboratories(){const labs=window.LABORATORIES||[];return <main className="container" style={{padding:'24px 0'}}><div className="actions"><a className="btn btn-secondary" href="/analysis">Aplikasi</a><form method="post" action="/superadmin/laboratories/clear-context"><input type="hidden" name="_token" value={csrf()}/><button className="btn btn-secondary">Platform</button></form></div><section className="card" style={{marginTop:16}}><h1>Laboratory Management</h1><form method="post" action="/superadmin/laboratories"><input type="hidden" name="_token" value={csrf()}/><div className="grid grid-2"><Field label="Kode LAB" name="code" type="text" required/><Field label="Nama Laboratorium" name="name" type="text" required/><Field label="Alamat" name="address" type="text"/><Field label="Telepon" name="phone" type="text"/><Field label="Email" name="email" type="email"/><Field label="Nama Admin" name="admin_name" type="text" required/><Field label="Email Admin" name="admin_email" type="email" required/><Field label="Password Admin" name="admin_password" type="password" required/></div><button className="btn btn-primary">Buat Laboratorium + Admin</button></form></section><section className="card"><div className="table-wrap"><table className="table"><thead><tr><th>Kode</th><th>Laboratorium</th><th>Users</th><th>Status</th><th>Akses</th></tr></thead><tbody>{labs.map(l=><tr key={l.id}><td>{l.code}</td><td>{l.name}</td><td>{l.users_count}</td><td>{l.active?'Aktif':'Nonaktif'}</td><td>{l.active?<form method="post" action={`/superadmin/laboratories/${l.id}/switch`}><input type="hidden" name="_token" value={csrf()}/><button className="btn btn-primary">Masuk</button></form>:null}</td></tr>)}</tbody></table></div></section></main>}

function ReportPrint(){const r=window.REPORT_DATA||{};return <main className="container" style={{padding:'20px 0'}}><div className="actions no-print"><button className="btn btn-primary" onClick={()=>window.print()}>Cetak / Simpan PDF</button><button className="btn btn-secondary" onClick={()=>history.back()}>Kembali</button></div><article className="card" style={{marginTop:16}}><header style={{display:'flex',justifyContent:'space-between',gap:20,borderBottom:'2px solid #172033',paddingBottom:12}}><div><h1>LABORATORY ANALYSIS REPORT</h1><div>Analisa {r.parameter}</div></div><div><b>No. Laporan</b><br/>{r.report_number||'-'}</div></header><h2>Identitas Analisis</h2><table className="table"><tbody>{[['Kode Sample',r.sample_code],['Parameter',r.parameter],['Metode',r.method],['Analis',r.analyst],['Tanggal Analisis',r.analysed_at],['Status',r.status]].map(x=><tr key={x[0]}><th>{x[0]}</th><td>{x[1]||'-'}</td></tr>)}</tbody></table><h2>Hasil</h2><table className="table"><tbody><tr><th>Parameter</th><th>Hasil</th><th>Satuan</th></tr><tr><td>{r.parameter}</td><td><b>{r.calculation?.result??'-'}</b></td><td>mg/L</td></tr></tbody></table><h2>Approval</h2><table className="table"><tbody><tr><th>Approved by</th><td>{r.approved_by||'-'}</td></tr><tr><th>Approved at</th><td>{r.approved_at||'-'}</td></tr></tbody></table></article></main>}

function ReportPrintOld(){return <div className="container" style={{padding:'20px 0'}}><div className="actions no-print"><button className="btn btn-primary" onClick={()=>window.print()}>Cetak / Simpan PDF</button><button className="btn btn-secondary" onClick={()=>history.back()}>Kembali</button></div><div className="card"><h1>Laboratory Analysis Report</h1><p>Gunakan dialog print browser → <b>Save as PDF</b>.</p></div></div>}

const root=document.getElementById('react-root');if(root){const page=document.body.dataset.page;const view=page==='report'?<ReportPrint/>:page==='login'?<Login/>:page==='users'?<Users/>:page==='laboratories'?<Laboratories/>:page==='samples'?<Master type="samples"/>:page==='reagents'?<Master type="reagents"/>:page==='instruments'?<Master type="instruments"/>:<AnalysisApp/>;createRoot(root).render(view);}
