import React,{useState}from'react';import{createRoot}from'react-dom/client';import'../css/app.css';

const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.content;
async function post(url,data={},method='POST'){const r=await fetch(url,{method,headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrf(),'Accept':'application/json'},body:JSON.stringify(data)});if(r.redirected)location.href=r.url;return r;}

function Field({label,name,type='number',required=false,value,onChange}){return <div className="field"><label>{label}</label><input name={name} type={type} step={type==='number'?'any':undefined} required={required} value={value??''} onChange={onChange}/></div>}

function AnalysisApp(){const[doForm,setDoForm]=useState({sample_code:'',thiosulfate_ml:'',thiosulfate_duplo_ml:'',normality:'',winkler_volume_ml:'',reagent_mnso4_ml:'1',reagent_alkali_ml:'1',aliquot_ml:'50'});const[bodForm,setBodForm]=useState({sample_code:'',a1:'',a2:'',b1:'',b2:'',vb:'',vc:'',p:'',sample_ph:'',sample_temperature:'',storage_temperature:'',storage_hours:'',gga_bod:''});const[message,setMessage]=useState('');
const set=(setter)=>(e)=>setter(v=>({...v,[e.target.name]:e.target.value}));
const submit=(url,data)=>async e=>{e.preventDefault();setMessage('Memproses...');const r=await post(url,data);setMessage(r.ok?'Data berhasil diproses.':'Validasi atau proses gagal.');if(r.ok)location.reload()};
return <div className="app-shell"><header className="topbar"><div className="container topbar-inner"><div><b>Laboratory Analysis</b><div style={{fontSize:12,opacity:.85}}>DO · BOD₅ · QC · Uncertainty</div></div><div>{window.LAB_USER_NAME||'User'} · {window.LAB_USER_ROLE||''}</div></div></header><main className="container" style={{padding:'22px 0 40px'}}><div className="actions no-print" style={{marginBottom:16}}><a className="btn btn-secondary" href="/analysis">Dashboard</a><a className="btn btn-secondary" href="/superadmin/laboratories">Laboratorium</a><form method="post" action="/logout"><input type="hidden" name="_token" value={csrf()}/><button className="btn btn-secondary">Logout</button></form></div>{message&&<div className="card" style={{marginBottom:16}}>{message}</div>}<div className="grid grid-2"><section className="card"><h2>Analisis DO</h2><form onSubmit={submit('/analysis/do',doForm)}><div className="grid grid-2">{Object.entries(doForm).map(([k,v])=><Field key={k} label={k.replaceAll('_',' ')} name={k} required={!k.includes('duplo')} value={v} onChange={set(setDoForm)}/>)}</div><button className="btn btn-primary">Hitung DO</button></form></section><section className="card"><h2>Analisis BOD₅</h2><form onSubmit={submit('/analysis/bod',bodForm)}><div className="grid grid-2">{Object.entries(bodForm).map(([k,v])=><Field key={k} label={k.replaceAll('_',' ')} name={k} required={['sample_code','a1','a2','b1','b2','vb','vc','p'].includes(k)} value={v} onChange={set(setBodForm)}/>)}</div><button className="btn btn-primary">Hitung & Simpan BOD₅</button></form></section></div><section className="card" style={{marginTop:16}}><h2>Ketidakpastian Top-Down</h2><p style={{color:'#667085'}}>Gunakan data precision dan bias hasil validasi/QC.</p><a className="btn btn-secondary" href="/analysis">Buka modul uncertainty</a></section></main></div>}

function ReportPrint(){return <div className="container" style={{padding:'20px 0'}}><div className="actions no-print"><button className="btn btn-primary" onClick={()=>window.print()}>Cetak / Simpan PDF</button><button className="btn btn-secondary" onClick={()=>history.back()}>Kembali</button></div><div className="card"><h1>Laboratory Analysis Report</h1><p>Gunakan dialog print browser → <b>Save as PDF</b>.</p></div></div>}

const root=document.getElementById('react-root');if(root)createRoot(root).render(document.body.dataset.page==='report'?<ReportPrint/>:<AnalysisApp/>);
