<?php
namespace Tests\Feature;
use Tests\TestCase;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\Hash;use Illuminate\Support\Facades\Notification;use App\Models\{Laboratory,Client,ClientUser,AnalysisRun};use App\Notifications\ApprovedReportNotification;
class ClientPortalTest extends TestCase {
 use RefreshDatabase;
 private function seedBase():array{$lab=Laboratory::create(['code'=>'LAB-T','name'=>'Lab Test','active'=>true]);$a=Client::withoutGlobalScopes()->create(['laboratory_id'=>$lab->id,'code'=>'C-A','name'=>'Client A','active'=>true]);$b=Client::withoutGlobalScopes()->create(['laboratory_id'=>$lab->id,'code'=>'C-B','name'=>'Client B','active'=>true]);$ua=ClientUser::create(['laboratory_id'=>$lab->id,'client_id'=>$a->id,'name'=>'User A','email'=>'a@example.test','password_hash'=>Hash::make('password123'),'role'=>'client_admin','active'=>true]);return compact('lab','a','b','ua');}
 public function test_client_cannot_view_another_clients_report():void{$x=$this->seedBase();$run=AnalysisRun::withoutGlobalScopes()->create(['laboratory_id'=>$x['lab']->id,'client_id'=>$x['b']->id,'sample_code'=>'S-B','parameter'=>'DO','method_version'=>'TEST','analyst'=>'Lab','analysed_at'=>now(),'calculation'=>['result'=>5.2],'status'=>'APPROVED']);$this->withSession(['client_user'=>['id'=>$x['ua']->id,'client_id'=>$x['a']->id,'laboratory_id'=>$x['lab']->id]])->get('/client/reports/'.$run->id)->assertNotFound();}
 public function test_client_cannot_view_unapproved_report():void{$x=$this->seedBase();$run=AnalysisRun::withoutGlobalScopes()->create(['laboratory_id'=>$x['lab']->id,'client_id'=>$x['a']->id,'sample_code'=>'S-A','parameter'=>'DO','method_version'=>'TEST','analyst'=>'Lab','analysed_at'=>now(),'calculation'=>['result'=>5.2],'status'=>'DRAFT']);$this->withSession(['client_user'=>['id'=>$x['ua']->id,'client_id'=>$x['a']->id,'laboratory_id'=>$x['lab']->id]])->get('/client/reports/'.$run->id)->assertNotFound();}
 public function test_approval_sends_notification_for_assigned_client():void{Notification::fake();$x=$this->seedBase();$run=AnalysisRun::withoutGlobalScopes()->create(['laboratory_id'=>$x['lab']->id,'client_id'=>$x['a']->id,'sample_code'=>'S-A','parameter'=>'DO','method_version'=>'TEST','analyst'=>'Lab','analysed_at'=>now(),'calculation'=>['result'=>5.2],'status'=>'READY_FOR_REVIEW']);app(\App\Services\ApprovalService::class)->review($run,'Supervisor','APPROVED');$this->assertDatabaseHas('analysis_runs',['id'=>$run->id,'status'=>'APPROVED']);Notification::assertSentOnDemand(ApprovedReportNotification::class,function($notification,$channels,$notifiable) use($x){return $notifiable->routes['mail']==='a@example.test'&&$notification->analysis->id!==null;});}
}
